### ISSUE TITLE
添加学在吉大桌面客户端

### ISSUE THREAD

**Issue by 1939323749** [userElaina/Outlast-JLU-DLC#5]
## 学在吉大桌面客户端
简介:
学在吉大视频下载器/H5播放器
基于[学在吉大视频下载器/H5播放器](https://github.com/RikaCelery/StudyAtJlu)

功能
- 视频筛选(按课程，按学期)
- 视频下载(按课程，按学期)
- 自动分类(保存文件夹/课程名/日期/视频类型.MP4)
- 跳过已下载文件(没得写了，凑字数)
- 播放器(同步播放，可拖动进度条)

项目地址:https://github.com/RikaCelery/StudyAtJLU_Desktop
应该很有用,而且正在积极维护中

**Comment by userElaina** [comment]
好的，谢谢您提供的信息

**Comment by userElaina** [comment]
[fb7f81a](https://github.com/userElaina/Outlast-JLU-DLC/commit/fb7f81aae378e890bf1176444795fd2048cb61a6)
